service: serverless-blog-cms

provider:
  name: aws
  runtime: nodejs12.x

plugins:  
  - serverless-webpack
  - serverless-offline

functions:
  getAllPosts:
    handler: src/handlers/getAllPosts.handler
    events:
      - http: GET posts

  getPostBySlug:
    handler: src/handlers/getPostBySlug.handler
    events:
      - http: GET post/{slug}
